version: '3'
services:
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules
      - ./server:/app