version: '3'
services:
  nginx:
    depends_on:
      - mdlsvr
      - ddlsvr
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3030:80'
  ddlsvr:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./ddlsvr
    volumes:
      - /app/node_modules
      - ./ddlsvr:/app
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  mdlsvr:
    build:
      dockerfile: Dockerfile.dev
      context: ./mdlsvr
    volumes:
      - /app/node_modules
      - ./mdlsvr:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  trnsvr:
    depends_on:
      - postgres
#    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./trnsvr
    volumes:
      - ./trnsvr:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432