# Specify a base image
FROM node:14.14.0-alpine

# Set working directory
WORKDIR '/app'

# Install depenendencies
COPY package.json .
RUN npm install

# Copy rest (= rebuild only when dependencies change)
COPY . .

# Default command
CMD ["npm", "run", "start"]